apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: controller
  newName: public.ecr.aws/os-partners/neuron-openshift/operator
  newTag: v1.3.0

resources:
- manager.yaml

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- files:
  - neuron_scheduler_config.yaml
  name: neuron-scheduler-config
  options:
    disableNameSuffixHash: true

patches:
- path: manager_config_patch.yaml
